apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: dpd-service
build:
  artifacts:
    - image: rg.fr-par.scw.cloud/cellarcollective/dpd-service
      jib:
        args: [-Pjib]

  tagPolicy:
    gitCommit: {}
        
deploy:
  kubectl:
    manifests:
      - .k8s/dev/dpd-service.yaml

