logging:
  level:
    org.springframework.security: INFO
    co.cellarcollective: DEBUG

ribbon:
  http:
    client:
      enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 160000

spring:
  profiles: local
  data:
    mongodb:
      uri: mongodb://localhost:27018
      database: dpd-service

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

server:
  version: '@project.version@'
  servlet:
    context-path: /dpd
  port: 8080