
GET http://localhost:20000/dpd/scenario/
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

GET http://localhost:20000/dpd/scenario/HOME-PICKING-COMPLETE
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:20000/dpd/scenario/
Content-Type: application/json

{
  "name": "HOME-PICKING-TRANSIT",
  "replayEvents": [
    {
      "delay": 1,
      "event": {
        "traceEventCODE": "REC",
        "traceEventDescription": "Recolhido no cliente"
      }
    },
    {
      "delay": 2,
      "event": {
        "traceEventCODE": "PEC",
        "traceEventDescription": "Entrada em armazém"
      }
    },
    {
      "delay": 3,
      "event": {
        "traceEventCODE": "OFD",
        "traceEventDescription": "Em distribuição"
      }
    }
  ]
}

###

DELETE http://localhost:20000/dpd/scenario/HOME-PICKING-CANCELLED-2
Content-Type: application/json