
GET http://localhost:20000/dpd/tracking/
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

GET http://localhost:20000/dpd/tracking/097253000000130
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

GET http://localhost:20000/dpd/tracking/097253000000846%3B097253000000854?live=true
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###
# Use %3B to encode ; for deliveries with multiple volumes
POST http://localhost:20000/dpd/tracking/
Content-Type: application/json

{
  "trackingScenario": "HOME-PICKING-COMPLETE-FAST",
  "trackingNumber": "097253000000846;097253000000854",
  "trackingMode": "MANUAL"
}

###

PUT http://localhost:20000/dpd/tracking/next/097253000000846%3B097253000000854
Content-Type: application/json

###

DELETE http://localhost:20000/dpd/tracking/097253000000130
Content-Type: application/json