
GET http://localhost:20000/dpd/tracking/
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

GET http://localhost:20000/dpd/tracking/097253000000130
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

GET http://localhost:20000/dpd/tracking/097253000000777?live=true
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:20000/dpd/tracking/
Content-Type: application/json

{
  "trackingScenario": "PICKUP-COMPLETE-FAST",
  "trackingNumber": "097253000000777",
  "trackingMode": "MANUAL"
}

###

PUT http://localhost:20000/dpd/tracking/next/097253000000777
Content-Type: application/json

###

DELETE http://localhost:20000/dpd/tracking/097253000000130
Content-Type: application/json