
GET http://localhost:20000/dpd/tracking/
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

GET http://localhost:20000/dpd/tracking/097253000000130
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

GET http://localhost:20000/dpd/tracking/097253000000130?live=true
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

POST http://localhost:20000/dpd/tracking/
Content-Type: application/json

{
  "trackingScenario": "HOME-PICKING-COMPLETE-FAST",
  "trackingNumber": "09725300000044M"
}

###

DELETE http://localhost:20000/dpd/tracking/097253000000130
Content-Type: application/json