apiVersion: v1
kind: Service
metadata:
  name: dpd-service
  labels:
    name: dpd-service
    project: cellarcollective
    tier: backend
    app: dpd-service
spec:
  ports:
    - protocol: TCP
      port: 20000
      targetPort: 20000
  selector:
    name: dpd-service-deployment
  type: ClusterIP   # Exposes the Service on a cluster-internal IP. Choosing this value makes the Service only reachable from within the cluster

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpd-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dpd-service-deployment
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: dpd-service-deployment
    spec:
      imagePullSecrets:
        - name: cellarcollective-container-registry
      containers:
        - env:
            # Generic Secrets
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: cellarcollective
                  key: mongodb_user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cellarcollective
                  key: mongodb_password

            #  Generic Configs
            - name: PROFILE
              valueFrom:
                configMapKeyRef:
                  name: cellarcollective
                  key: profile
          image: rg.fr-par.scw.cloud/cellarcollective/dpd-service:latest
          name: dpd-service
          ports:
            - containerPort: 20000
          resources: {}
          imagePullPolicy: Always
      restartPolicy: Always
